### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Pholey** [Morosko/atom-telegram#3]
`self.client.messages.receivedMessages(data.id, function(err) {console.log(err);});`

Where does this function come from? I'm having a hard time finding it's definition

**Comment by Morosko** [comment]
It's party of enrico's API so better have a look there. As far as I can remember it was in the messages directory.

**Comment by Pholey** [comment]
Drats.. Unfortunately it is undefined in his API for me (been staring at this for the last 10 or so hours tab-completing everything in nesh).. The object I receive from 'createClient.messages' has every function expected in the API docs of telegram except this one.. I had hoped maybe you implemented it yourself

**Comment by Pholey** [comment]
Drats.. Unfortunately it is undefined in his API for me (been staring at this for the last 10 or so hours tab-completing everything in nesh).. The object I receive from 'createClient.messages' has every function expected in the API docs of telegram except this one.. I had hoped maybe you implemented it yourself

**Comment by Pholey** [comment]
Drats.. Unfortunately it is undefined in his API for me (been staring at this for the last 10 or so hours tab-completing everything in nesh).. The object I receive from 'createClient.messages' has every function expected in the API docs of telegram except this one.. I had hoped maybe you implemented it yourself

**Comment by Pholey** [comment]
Drats.. Unfortunately it is undefined in his API for me (been staring at this for the last 10 or so hours tab-completing everything in nesh).. The object I receive from 'createClient.messages' has every function expected in the API docs of telegram except this one.. I had hoped maybe you implemented it yourself

**Comment by Morosko** [comment]
Well, just looked at my local repo and noticed that I've forgotten to push this function. Now I pushed it [here](https://github.com/Morosko/telegram.link/commit/8ec7ac5759037594f2b774952e1325cf26d33ee4). Have fun with it ;)

**Comment by Pholey** [comment]
@Morosko thank you! You have no idea how much of a life saver you are :+1:

**Comment by Pholey** [comment]
https://github.com/Morosko/atom-telegram/blob/master/package.json#L21

Something I just noticed... You may want to update your package.json to use your fork of telegram.link, or possibly submit a PR to telegram.link?

**Comment by Morosko** [comment]
Unfortunately enrico doesn't merge all I wrote :/
To be able to use my fork as dependency I'd have to submit a new npm package which is from my current point of view too much work for nothing. This project was a fun weekend project to learn about atom plugins and coffeescript. I don't want to take care of more packages.
But I encourage you to do it :)
You can then send it to me so I'll change my dependencies or you simply create a PR for it.
